### PR TITLE
Use actions/checkout@v3 token for git push to trigger other actions

### PR DESCRIPTION
**Pull request by houstonj1**
@devth I think this will configure git correctly on checkout, so we can push 🤞

### CODE REVIEW

**Comment by devth** [comment]
🤔 https://github.com/devth/helm-docker/actions/runs/4865123952/jobs/8675029542

**Comment by houstonj1** [comment]
@devth I found this - https://github.com/actions/checkout/issues/664#issuecomment-1152342086

Mind checking if that PAT has an expire date set? Other than that, we can try adding the specific repo to checkout and the branch to the checkout action config

**Comment by devth** [comment]
Nope, it doesn't have an expiration date!

**Comment by houstonj1** [comment]
Kinda lame it _needs_ one but, I guess that is good for security

**Comment by devth** [comment]
Let me provision a new one with exp date.

**Comment by devth** [comment]
Ok, new one is set. Expires in a year.

**Comment by houstonj1** [comment]
🎉 It worked, but we didn't get the tag with it.... Something to look at next

**Comment by devth** [comment]
Amazing! Thanks for fixing it.

Hope it can auto close the github issue too at some point.

**Pull request merged**
