### PR TITLE
Added jq to the toolset

### PR DESCRIPTION
**Pull request by Toflar**
As we're dealing with JSON quite a lot in the k8s environment, I find myself lost in JSON quite often e.g. to extract data from `kubectl get pod <podname> -o=json`. I know there's built in `jsonpath` support but sometimes I would like to combine outputs from different commands etc. which is where `jq` (https://stedolan.github.io/jq/) usually comes in super handy!
Wdyt?

### CODE REVIEW

**Comment by devth** [comment]
👍 LGTM I ❤️ `jq`! Thanks for contributing.

**Comment by Toflar** [comment]
Hey Trevor, any plans on treleasing that soon? Afaics Docker Hub is not updated yet (https://hub.docker.com/r/devth/helm/dockerfile) so I still don't have `jq` 😢 
Thanks for checking! 😄

**Comment by devth** [comment]
I retagged the commit and Docker Hub Automated Builds should have auto-rebuilt it but it didn't :/ 

Let me see if I can convince it to rebuilt or maybe make a new `latest` build.

**Comment by devth** [comment]
Ok a couple new builds in progress currently: https://hub.docker.com/r/devth/helm/builds

- I rebuilt `latest` - this always corresponds to most recent tag (except today's build which I manually triggered)
- Created a new rule to always build a `master` tag that corresponds with master (regardless of whether it's tagged or not)

**Comment by Toflar** [comment]
At the speed of light! Awesome, works like a charm now, thank you so much!

**Comment by devth** [comment]
Great! No problem 😁

**Pull request merged**
