### PR TITLE
Update gh actions

### PR DESCRIPTION
**Pull request by houstonj1**
This should fix the gh workflow publishing the new dockerfile changes to git.

### CODE REVIEW

**Comment by devth** [comment]
Thanks @houstonj1 !

**Comment by devth** [comment]
Btw, the Zap to auto open GH issues for new Helm was disabled. Just re-enabled it.

**Comment by devth** [comment]
Also: the other problem is the docker publish workflow won't trigger from the git tag, because the git tag is created by another action 😭

**Comment by houstonj1** [comment]
Thoughts in using a reusable workflow for the docker publish? 

The update helm workflow would be responsible for:
1. Gets the latest version, updates the repo and tags
2. Kick off the docker build workflow, with the tag as the input

**Comment by devth** [comment]
Sounds great! I was kinda thinking the same.

**Pull request merged**
