### PR TITLE
Try to fix failing git push

### PR DESCRIPTION
**Pull request by houstonj1**
Hoping to fix the git push steps here - so we can get images newer than v3.9.0

Not sure if this is going to work or not, might as well try! 😄

### CODE REVIEW

**Comment by devth** [comment]
Thanks @houstonj1! GH Actions are hard to debug :(

**Comment by devth** [comment]
No idea what this means 😓 something must have changed?

```
Deleting git tags for v3
Deleted tag 'v3' (was e6a9bd1)
fatal: could not read Username for 'https://github.com/': No such device or address
Error: Process completed with exit code 128.
```

https://github.com/devth/helm-docker/actions/runs/4853967489/jobs/8650777123

**Comment by devth** [comment]
Maybe I'll check out https://github.com/nektos/act for local dev / debugging.

**Comment by houstonj1** [comment]
@devth Now that this is setup to push to Docker with actions, I am wondering if the major version tagging is overly complex. Maybe we can just add a second push to the docker push to push that docker tag, rather than trying to get the git tagging working for a major version? Thoughts?

**Comment by devth** [comment]
Sure, makes sense. Let's try that for now.

**Comment by houstonj1** [comment]
@devth Let's do it :shipit:

**Comment by devth** [comment]
Yep, opening a new issue triggers it. Trying it: https://github.com/devth/helm-docker/issues/179

**Comment by devth** [comment]
Failed pushing: https://github.com/devth/helm-docker/actions/runs/4864701082/jobs/8674058881#step:5:8

**Comment by houstonj1** [comment]
Okay cool, so same issue. I am wondering if it has something to do with the git config. Going to do some research on this to see if I can find anything. 

I also know we need to use your PAT so the action is triggered off the tag push - so I will investigate that path more. 👍

**Pull request merged**
